# Generated by Django 4.0.7 on 2022-09-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_productspage_days_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
