# Generated by Django 4.0.7 on 2022-10-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_productspage_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snipcartsettings',
            name='api_key',
        ),
        migrations.AddField(
            model_name='snipcartsettings',
            name='snipcart_api_key',
            field=models.CharField(blank=True, help_text='The API Key used for Snipcart.', max_length=255, verbose_name='Snipcart API Key'),
        ),
    ]
