# Generated by Django 4.0.7 on 2022-10-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_snipcartsettings_api_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snipcartsettings',
            options={'verbose_name': 'Snipcart Settings'},
        ),
    ]
