# Generated by Django 4.0.7 on 2022-10-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_snipcartsettings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snipcartsettings',
            options={'verbose_name': 'Snipcart'},
        ),
    ]
